### ISSUE TITLE
Nothing renders

### ISSUE THREAD

**Issue by WarrenXiaGG** [OpenGGEngine/OpenGG-Project#35]

**Comment by javster101** [comment]
Thanks for giving more than enough info to fix the problem

**Comment by WarrenXiaGG** [comment]
no error is provided and all textures are loaded successfully. The code ran was pulled direct and has no modifications so idk what noteworthy info i should give you

**Comment by WarrenXiaGG** [comment]
I'm also curious whether the code displays anything on your screen

**Comment by javster101** [comment]
For me, it works absolutely fine

**Comment by WarrenXiaGG** [comment]
then ill blame intel iris graphics
