### ISSUE TITLE
Major Problem With Skybox Shader

### ISSUE THREAD

**Issue by WarrenXiaGG** [OpenGGEngine/OpenGG-Project#37]
Skybox shader does not load at all. This is confirmed on my laptop due to purposely erroneous skybox shader code appearing to compile successfully(ommited semicolons) and setting the color in skybox fragment shader not working at all. This is odd behavior as this does not affect gui shader. Does this affect anybody else's computers?

**Comment by javster101** [comment]
same on my desktop, but not new
