### ISSUE TITLE
Triggers

### ISSUE THREAD

**Issue by javster101** [OpenGGEngine/OpenGG-Project#53]

**Comment by ethanmak** [comment]
lol wut

**Comment by WarrenXiaGG** [comment]
what magic features are being concocted on the dev-jav branch

**Comment by javster101** [comment]
its MAGIC

**Comment by WarrenXiaGG** [comment]
obscure features trigger me

**Comment by WarrenXiaGG** [comment]
you know what also triggers me


errors: Exception in thread "main" java.lang.NoClassDefFoundError: com/opengg/core/io/input/KeyboardHandler

**Comment by javster101** [comment]
Oh yeah, i renamed the file but apparently netbeans cant push file name changes if they only have letters that change case

**Comment by javster101** [comment]
Btw, i added a bunch  of sick features to the repo, but you have to make your own branch like i did

**Comment by WarrenXiaGG** [comment]
So how do i fix this problem

**Comment by javster101** [comment]
Rename KeyBoardHandler to KeyboardHandler

**Comment by WarrenXiaGG** [comment]
its already like that in netbeans

**Comment by javster101** [comment]
Idk then

**Comment by WarrenXiaGG** [comment]
fixed
